### ISSUE TITLE
Error with Lora-E5.h file

### ISSUE THREAD

**Issue by kirstenjeanlee** [andresoliva/LoRa-E5#5]
Hi there,

I've been having an issue when verifying the Grove-Wio-E5_basic.ino file. I have attached an image of the error that I have getting below.

For context, I am using an Arduino UNO as my MCU and the Grove Wio E5 module for my device. 

![Capture](https://github.com/andresoliva/LoRa-E5/assets/102248142/ba9179e4-ab89-44ca-8ed7-07be32176a39)

Thanks!

**Comment by Love4yzp** [comment]
You may find the solution from this repo: 
https://github.com/disk91/Disk91_LoRaE5/blob/master/src/disk91_LoRaE5.h#L73

**Comment by andresoliva** [comment]
Hello @[kirstenjeanlee](https://github.com/kirstenjeanlee)
kirstenjeanlee. Sadly, I do not have an ArduinoUNO board to replicate the error. But the error is because of the following issue. This library uses the UART interface to implement the serial communication with the LoRa module (of course, you and the other users do not see this when you use the library). The code of the UART interface is not 100% the same as all the Arduino boards, and for this reason, things in the code will not work and need a case-by-case implementation depending on each device. 
[Love4yzp](https://github.com/Love4yzp) Has quoted a library that should work (you can also see how the communication implementation has been done). I will try to look at it this weekend, but because I do not have an Arduino UNO Board I cannot know if the solution will work.

**Comment by kirstenjeanlee** [comment]
Hi @andresoliva!

I have been able to get a hold of an Arduino Nano 33BLE which I believe is compatible with the library. So I hope this is alleviate the issues that I’m having. 

Thank you very much for you feedback!!!
